package ca.bcit.comp2613.coursematerial.sakila.model;

// Generated Jul 10, 2014 12:08:13 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * FilmList generated by hbm2java
 */
@Entity
@Table(name = "film_list", catalog = "sql345717")
public class FilmList implements java.io.Serializable {

	private FilmListId id;

	public FilmList() {
	}

	public FilmList(FilmListId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "fid", column = @Column(name = "FID")),
			@AttributeOverride(name = "title", column = @Column(name = "title")),
			@AttributeOverride(name = "description", column = @Column(name = "description")),
			@AttributeOverride(name = "category", column = @Column(name = "category")),
			@AttributeOverride(name = "price", column = @Column(name = "price")),
			@AttributeOverride(name = "length", column = @Column(name = "length")),
			@AttributeOverride(name = "rating", column = @Column(name = "rating")),
			@AttributeOverride(name = "actors", column = @Column(name = "actors")) })
	public FilmListId getId() {
		return this.id;
	}

	public void setId(FilmListId id) {
		this.id = id;
	}

}
