package ca.bcit.comp2613.coursematerial.sakila.model;

// Generated Jul 10, 2014 12:08:13 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SalesByStoreId generated by hbm2java
 */
@Embeddable
public class SalesByStoreId implements java.io.Serializable {

	private Integer store;
	private Integer manager;
	private Integer totalSales;

	public SalesByStoreId() {
	}

	public SalesByStoreId(Integer store, Integer manager, Integer totalSales) {
		this.store = store;
		this.manager = manager;
		this.totalSales = totalSales;
	}

	@Column(name = "store")
	public Integer getStore() {
		return this.store;
	}

	public void setStore(Integer store) {
		this.store = store;
	}

	@Column(name = "manager")
	public Integer getManager() {
		return this.manager;
	}

	public void setManager(Integer manager) {
		this.manager = manager;
	}

	@Column(name = "total_sales")
	public Integer getTotalSales() {
		return this.totalSales;
	}

	public void setTotalSales(Integer totalSales) {
		this.totalSales = totalSales;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SalesByStoreId))
			return false;
		SalesByStoreId castOther = (SalesByStoreId) other;

		return ((this.getStore() == castOther.getStore()) || (this.getStore() != null
				&& castOther.getStore() != null && this.getStore().equals(
				castOther.getStore())))
				&& ((this.getManager() == castOther.getManager()) || (this
						.getManager() != null && castOther.getManager() != null && this
						.getManager().equals(castOther.getManager())))
				&& ((this.getTotalSales() == castOther.getTotalSales()) || (this
						.getTotalSales() != null
						&& castOther.getTotalSales() != null && this
						.getTotalSales().equals(castOther.getTotalSales())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getStore() == null ? 0 : this.getStore().hashCode());
		result = 37 * result
				+ (getManager() == null ? 0 : this.getManager().hashCode());
		result = 37
				* result
				+ (getTotalSales() == null ? 0 : this.getTotalSales()
						.hashCode());
		return result;
	}

}
