package ca.bcit.comp2613.coursematerial.sakila.model;

// Generated Jul 10, 2014 9:29:20 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TeacherStudentId generated by hbm2java
 */
@Embeddable
public class TeacherStudentId implements java.io.Serializable {

	private String teacherId;
	private long studentId;

	public TeacherStudentId() {
	}

	public TeacherStudentId(String teacherId, long studentId) {
		this.teacherId = teacherId;
		this.studentId = studentId;
	}

	@Column(name = "teacher_id", nullable = false)
	public String getTeacherId() {
		return this.teacherId;
	}

	public void setTeacherId(String teacherId) {
		this.teacherId = teacherId;
	}

	@Column(name = "student_id", nullable = false)
	public long getStudentId() {
		return this.studentId;
	}

	public void setStudentId(long studentId) {
		this.studentId = studentId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TeacherStudentId))
			return false;
		TeacherStudentId castOther = (TeacherStudentId) other;

		return ((this.getTeacherId() == castOther.getTeacherId()) || (this
				.getTeacherId() != null && castOther.getTeacherId() != null && this
				.getTeacherId().equals(castOther.getTeacherId())))
				&& (this.getStudentId() == castOther.getStudentId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTeacherId() == null ? 0 : this.getTeacherId().hashCode());
		result = 37 * result + (int) this.getStudentId();
		return result;
	}

}
