package ca.bcit.comp2613.coursematerial.sakila.model;

// Generated Jul 10, 2014 9:29:20 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TeacherStudent generated by hbm2java
 */
@Entity
@Table(name = "teacher_student", catalog = "sakila")
public class TeacherStudent implements java.io.Serializable {

	private TeacherStudentId id;
	private Student student;
	private Teacher teacher;

	public TeacherStudent() {
	}

	public TeacherStudent(TeacherStudentId id, Student student, Teacher teacher) {
		this.id = id;
		this.student = student;
		this.teacher = teacher;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "teacherId", column = @Column(name = "teacher_id", nullable = false)),
			@AttributeOverride(name = "studentId", column = @Column(name = "student_id", nullable = false)) })
	public TeacherStudentId getId() {
		return this.id;
	}

	public void setId(TeacherStudentId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "student_id", nullable = false, insertable = false, updatable = false)
	public Student getStudent() {
		return this.student;
	}

	public void setStudent(Student student) {
		this.student = student;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "teacher_id", nullable = false, insertable = false, updatable = false)
	public Teacher getTeacher() {
		return this.teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

}
